version: '3.8'
services:
  atom-dl-plf:
    build:
      context: .
      args:
        - PUID=621
        - PGID=1000
    container_name: atom-dl-plf
    volumes:
      - ./app-atom-dl/data:/home/atom-dl/.local/share/atom-dl
      - ./app-atom-dl/config:/home/atom-dl/.config/atom-dl
      - ${ATOM_DL_DOWNLOADS_PATH}:/atom-dl-downloads
      - "/etc/localtime:/etc/localtime:ro"
    command: ["atom-dl", "-plf"]
  atom-dl-fjd:
    build:
      context: .
      args:
        - PUID=621
        - PGID=1000
    container_name: atom-dl-fjd
    volumes:
      - ./app-atom-dl/data:/home/atom-dl/.local/share/atom-dl
      - ./app-atom-dl/config:/home/atom-dl/.config/atom-dl
      - ${ATOM_DL_DOWNLOADS_PATH}:/atom-dl-downloads
      - "/etc/localtime:/etc/localtime:ro"
    command: ["atom-dl", "-fjd"]
