version: '3.8'

services:
  atom-dl:
    build:
      context: .
      args:
        - PUID=621
        - PGID=1000
    container_name: atom-dl
    volumes:
      - ./app-atom-dl/data:/home/atom-dl/.local/share/atom-dl
      - ./app-atom-dl/config:/home/atom-dl/.config/atom-dl
      - ${ATOM_DL_DOWNLOADS_PATH}:/atom-dl-downloads