version: '3.8'

services:
  atom-dl:
    build: .
    user: "621:1000"
    container_name: atom-dl
    volumes:
      - ./app-atom-dl/data:/root/.local/share/atom-dl
      - ./app-atom-dl/config:/root/.config/atom-dl