from atom_dl.download_service.feed_downloader.comicmafia import ComicmafiaFD
from atom_dl.download_service.feed_downloader.ibooks import IbooksFD
from atom_dl.download_service.feed_downloader.languagelearning import LanguagelearningFD
